### ISSUE TITLE
pg_socket

### ISSUE THREAD

**Issue by sm2017** [reactphp/event-loop#121]
How can I `addReadStream` to `pg_socket`?

I try the following code on PHP 7.0

```php
$loop = React\EventLoop\Factory::create();
$connection = pg_connect("host=localhost port=5432 dbname=mary");
$socket = pg_socket($connection);
$loop->addReadStream($socket , function (){
  echo "READ EVENT\n";
});

pg_send_query($connection , "select * from authors;");
$loop->run();
```

The code works well when I choose `Select` But when I run code with `Event` extension I have `Segmentation fault`

More details on http://php.net/manual/en/function.pg-socket.php

**Comment by clue** [comment]
Thanks for reporting and letting us know!

Not all resource types are supported by all event loop implementation, this is known limitation that should also be covered as part of our documentation.

That being said, the `ext-event` should probably probably signal this in a reasonable manner instead of causing a segfault in this case. I would suggest filing an issue upstream (please report back!) and/or using another event loop implementation in the meantime :+1: 

I hope this helps! :+1:
