### ISSUE TITLE
Process stops responding

### ISSUE THREAD

**Issue by lazychaser** [reactphp/event-loop#176]
I'm using latest react with ratchet/pawl for sockets and clue/socks-react for running via proxy on Ubuntu 16.04.

I tried ExtEventLoop and basic stream select loops.

At some point, when I'm trying to write something to stream, whole process blocks and starts to use 100% CPU. Seems like it falls into infinite loop.

I set a timer that should stop loop after a while, but it never gets called, so as any other timers.

Also, I'm using pcntl timer with async signals to stop the script, but the handler is never called.

Not related to the question: what is the better loop for PHP7.2? I noticed that memory usage of script with ExtEventLoop is growing much faster.

**Comment by clue** [comment]
Bummer, this shouldn't have happened!

We're not aware of any memory issues or possible crashes, so this this really shouldn't have happened. Can you gist your code and check you're running the latest versions (`composer outdated`)?

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:

> At some point, when I'm trying to write something to stream, whole process blocks and starts to use 100% CPU. Seems like it falls into infinite loop.
>
> I set a timer that should stop loop after a while, but it never gets called, so as any other timers.

We're not aware of any such issues afaict, but the description sounds more like an issue in some internal PHP function as the event-loop is apparently no longer involved. We've recently worked around a PHP bug to fix TLS 1.3 streams via https://github.com/reactphp/socket/pull/186, so this might as well have fixed this :+1:
