### ISSUE TITLE
Adding swoole

### ISSUE THREAD

**Issue by josephmiller2000** [reactphp/event-loop#187]
Hello any plan adding ?

https://pecl.php.net/package/swoole as default events?

**Comment by WyriHaximus** [comment]
There are currently no plans, but we're always open for PR adding new event loops

**Comment by clue** [comment]
Have you seen https://github.com/swoole/library/blob/master/src/Swoole/Driver/React.php?

Swoole and ReactPHP are somewhat similar in what they're trying to achieve, so I agree that an adapter implementation makes perfect sense to improve interoperability between both.

Given the above implementation already exists, I don't think there's much that needs to be done here? I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:

**Comment by zek** [comment]
@clue The link you gave does not exist anymore :(

**Comment by clue** [comment]
@zek I would suggest asking the Swoole folks to see what happened to their driver implementation 👍

Otherwise, it looks like building an adapter between Swoole and ReactPHP should be fairly straight forward based on https://www.swoole.co.uk/docs/modules/swoole-event-add and ReactPHP's `LoopInterface`. Go for it? :shipit:

**Comment by TiMESPLiNTER** [comment]
Quite outdated but I thought I link it here if anyone is interested in an example how it (used to) works with Swoole:

https://github.com/n3vrax/reactphp-swoole-eventloop
