### ISSUE TITLE
Problems using fd with resource.

### ISSUE THREAD

**Issue by Provoker** [reactphp/event-loop#191]
When using fd and resource there is a chance to get the same $key in the ExtEventLoop::addReadStream() method and similar methods, which leads to serious problems reading, writing and responding to events of another connection.

Small example
```
$fp1 = fsockopen("php.net", 80, $errno, $errstr, 30);
$fp2 = fsockopen("php.net", 80, $errno, $errstr, 30);

// [fp1] Resource id: 4, fd: 3
printf("[fp1] Resource id: %d, fd: %d\n", (int)$fp1, EventUtil::getSocketFd($fp1));

// [fp2] Resource id: 5, fd: 4
printf("[fp2] Resource id: %d, fd: %d\n", (int)$fp2, EventUtil::getSocketFd($fp2));

// bool(true)
var_dump((int)$fp1 === (int)EventUtil::getSocketFd($fp2));
```

This example demonstrates that we get the same $key when using the $fp1 resource and the file descriptor from $fp2, despite the fact that these are different connections.

**Comment by clue** [comment]
@Provoker Thanks for reporting, I think I understand where you're coming from.

As per https://github.com/reactphp/event-loop#addreadstream, the `addReadStream()` method MUST be called with a valid stream resource. As such, I don't see how this could be an issue in this library. We only rely on the resource IDs to be unique and do not care about the underlying file descriptor.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by Provoker** [comment]
The php-event can accept not only the resource, but also fd as an argument.
ExtEventLoop::addReadStream() can also accept fd, and it works until the situation described above occurs.
Probably you did not suspect that the event-loop can be used in this way.

Can we expect full support for fd? To do this, you only need to change the algorithm for generating $key for the resources collections.

**Comment by clue** [comment]
I understand that the underlying event loop implementation may or may not support this. However, this is something that this project has never supported. Among others, this is done for consistency reasons, because not all loop implementations support this and also because not all platforms use the concept of FDs for everything.

If you want to work with a file descriptor number, you can always create a stream resource from it in php like this:

```php
$stream = fopen('php://fd/8', 'r');
```

This stream resource can be added through the `addReadStream()` method just fine.

Adding support for plain FDs will introduce a BC break to our interfaces, but it's certainly something that *could* be done if if provides enough value. You can always create a PR if you feel it's worth it and I'm happy to help reviewing :+1:

**Comment by Provoker** [comment]
Thanks for your reply.
