### ISSUE TITLE
Stop Instance of Loop without stopping all instances

### ISSUE THREAD

**Issue by Ross-C** [reactphp/event-loop#200]
Hi, Is there away to stop a single instance of an event loop without stopping all instances if you need to keep one running?

Many thanks

**Comment by clue** [comment]
The following piece of code will stop exactly this loop instance:

```php
$loop->stop();
```

In a normal application you should not usually have multiple loop instances at once, so I'm not sure what you're trying to achieve exactly.

In case you want to cancel a "timer" instead of "loop", you can simply stop them like this:

```php
$timer = $loop->addPeriodicTimer(0.1, function () {
    echo 'hello' . microtime(true) . PHP_EOL;
});

$loop->addTimer(1.0, function () use ($loop, $timer) {
    $loop->cancelTimer($timer);
});
```

I hope this helps :+1:

**Comment by Ross-C** [comment]
Hi thanks for your help with this I am using the following repo https://github.com/enniel/ami it uses a reactloop for two actions one is for a command called ami:listen ( a laravel artisan command) and the other is an action.  The listen commend need to stay running to fire events but when i trigger an action it hits the reactloop stop() method which also stops the listen loop.  It sounds like this is the expected behaviour of the reactloop and I need to try and fix it by implementing timers - thanks for your help 👍
