### ISSUE TITLE
1.0 release 

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/event-loop#33]
Event loop 0.4 is very stable and there aren't any big BC breaks planned (maybe #30) so what is stopping us from putting a list of small things together we want in 1.0 and work towards that so we can tag 1.0 and push any major redesigns to 2.0?

**Comment by mbonneau** [comment]
:+1: I would like to see 1.0 tagged the way it is now. If there is to be more discussion on #30, let it wait until the next minor release where it can be deprecated until 2.0. The react libraries - especially event-loop and stream are great libraries that I use in production regularly. I would hate to think that people don't use them simply because they are still pre v1.

**Comment by daltones** [comment]
:+1: for 1.0 release!

**Comment by mbonneau** [comment]
@cboden, @clue  - what is needed to get to 1.0?

**Comment by davidwdan** [comment]
:+1:

**Comment by adamlc** [comment]
:+1:

**Comment by clue** [comment]
See #101 for new roadmap to v1.0.0 :+1:
