### ISSUE TITLE
Recommanded Loop implementation for php7

### ISSUE THREAD

**Issue by tkleinhakisa** [reactphp/event-loop#55]
Hi,

i'm trying to upgrade my app to php7. I used libevent and the matching pecl extension which is not available anymore for php7

What would you recommend ?
- use the libevent extension fork from https://github.com/expressif/pecl-event-libevent ?
- use LibEvLoop (https://github.com/m4rw3r/php-libev) last commit is from 2013 so i doubt it is ready for php7
- use the pecl event extension which seems to be ready for php7 (i have not tried) https://pecl.php.net/package-changelog.php?package=event&release=2.1.0

Did some of you make the switch already ?
What solution did you choose ?

Thank you for the effort in ReactPHP

**Comment by geki-yaba** [comment]
I used expressif's version with a patch to make pecl-libevent work with php7. Without the patch my server instance would just crash on startup. Though, causing one memory leak.

Today I switched to pecl-event-2.2.1 (master snapshot) for its issue 31 [0]. pecl-event supports php7 since version 2.1.0. For now, it looks promising; the server instance started and could be terminated with ctrl-c. So, running as a daemon works, which only works with a libevent backend.

[0] https://bitbucket.org/osmanov/pecl-event/issues/31

**Comment by leric** [comment]
There's another libev binding for php in pecl which is actively maintained, and php7 compatible, could be a good choice for another event-loop implementation.
http://pecl.php.net/package/ev

**Comment by clue** [comment]
The libevent extension does not currently support PHP7. There's ongoing effort to update libevent to support PHP7 in php/pecl-event-libevent#2. However, the current version occasionally segfaults. This could not be observed in earlier version, so it is believed that this is a bug in libevent, rather than React.
As such, there's little we can do here. Discussion about this is probably best directed at https://github.com/reactphp/event-loop/issues/40.

In the meantime, you may want to check out the "event" extension. We've seen reports of people successfully using this on PHP7.

**Comment by clue** [comment]
> In the meantime, you may want to check out the "event" extension. We've seen reports of people successfully using this on PHP7.

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:

**Comment by rhclayto** [comment]
I created a pull request adding support for pecl-ev (http://pecl.php.net/package/ev): 

https://github.com/reactphp/event-loop/pull/83
