### ISSUE TITLE
PHPUnit Test Fail, Windows 10, PHP 7

### ISSUE THREAD

**Issue by internalsystemerror** [reactphp/event-loop#71]
Not sure if this is known, trying to debug an issue elsewhere in React, so running the test suites on all installed components... Please ignore/close this issue if unhelpful/not required...

```
PHPUnit 4.8.32 by Sebastian Bergmann and contributors.

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 145 ( 43%)
SSSSSSSSSSSSSSSSSSSSSSS..SSSSSS...........................SSSSS 126 / 145 ( 86%)
SSSSSSSSSSSSSF.....

Time: 846 ms, Memory: 8.00MB

There was 1 failure:

1) React\Tests\EventLoop\Timer\StreamSelectTimerTest::testAddTimer
Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 145, Assertions: 44, Failures: 1, Skipped: 110.
```

Using version 0.4.2 (dev-master has this error along with another as shown below:

```
PHPUnit 4.8.32 by Sebastian Bergmann and contributors.

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 146 ( 43%)
SSSSSSSSSSSSSSSSSSSSSSS.SSSSSS............................SSSSS 126 / 146 ( 86%)
SSSSSSSSSSSSSFF.....

Time: 1.84 seconds, Memory: 8.00MB

There were 2 failures:

1) React\Tests\EventLoop\Timer\StreamSelectTimerTest::testAddTimer
Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

2) React\Tests\EventLoop\Timer\StreamSelectTimerTest::testAddPeriodicTimer
Expectation failed for method name is equal to <string:__invoke> when invoked 3 time(s).
Method was expected to be called 3 times, actually called 2 times.

FAILURES!
Tests: 146, Assertions: 44, Failures: 2, Skipped: 110.
```

**Comment by clue** [comment]
@internalsystemerror thanks for reporting! :+1:

Unfortunately I do not have a system to test this on, so I guess we could use some help to track this down.

Which version of Windows has this been tested on, can you try some variations on this, can others confirm this issue?

Can you try running the test suite multiple times, could this perhaps be flaky?

The test assumptions look a bit flaky because they assume quite accurate timing which highly depends on your system. (See https://github.com/reactphp/event-loop/blob/master/tests/Timer/AbstractTimerTest.php for more details.)

Also, the tests have been updates as part of #72 (master branch only), does this affect your results?

**Comment by clue** [comment]
Closing this due to a lack of feedback and because this may have been resolved in the meantime. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by internalsystemerror** [comment]
@clue Will do, iirc this was caused upstream by https://github.com/reactphp/dns/issues/44 and may in fact be resolved now
